---

# DEBIAN

python_package: 'python3'

# PHP

php8_ini_directives_fpm:
  upload_max_filesize: "8M"
  post_max_size: "8M"

php8_version: 8.1
php8_enable_fpm: yes

php8_versioned_extensions:
  - zip
  - intl
  - curl
  - mysql
  - gd
  - xml
  - mbstring
  - amqp
  - bcmath

php8_fpm_pool_enabled: yes
php8_fpm_pool_name: www
php8_fpm_pool_listen: "/run/php/php{{ php8_version }}-fpm.sock"
php8_fpm_pool_listen_mode: "0660"
php8_fpm_pool_pm: static
php8_fpm_pool_status_path: /status
php8_fpm_pool_pm_max_children: 128
php8_fpm_pool_pm_max_requests: 512
php8_fpm_pool_catch_workers_output: yes

# MYSQL

mariadb_version: '10.6'
mariadb_config_template: "{{ inventory_dir }}/roles/webserver/templates/my.cnf.j2"
mariadb_max_allowed_packet:      "64M"
mariadb_innodb_buffer_pool_size: 592M
mariadb_charset: utf8mb4
mariadb_collation: utf8mb4_unicode_520_ci
mariadb_key_buffer_size: 32M
mariadb_query_cache_size: 0
mariadb_innodb_log_file_size: 128M
mariadb_wait_timeout: 600
mariadb_slow_query_log_enabled: true
mariadb_long_query_time: 2

mariadb_origin: upstream
mariadb_vendor: mariadb

mariadb_bind_address: "{{ global_db_ip }}"
mariadb_port: 3306
mariadb_socket: /var/run/mysqld/mysqld.sock

mariadb_error_log: "/var/log/mysql/error.log"
mariadb_slow_query_log: "/var/log/mysql/mysql_slow.log"

bashrc_users:
  - "provision"

# NGINX
nginx_www_dir: "/var/www"
nginx_dhparam_bits: 4096
nginx_http_headers:
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
nginx_http_headers_default:
  Content-Security-Policy: "default-src 'self'; form-action 'self'; frame-ancestors 'none'"
  Referrer-Policy: "no-referrer, strict-origin-when-cross-origin"
  Strict-Transport-Security: max-age=15768000
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-Xss-Protection: "1; mode=block"

# Certbot
certbot_create_method: webroot
certbot_create_if_missing: yes
certbot_admin_email: markmeijerman@gmail.com
certbot_auto_renew: no  # we use our own task
certbot_auto_renew_options: "--quiet --no-self-upgrade --renew-hook 'sudo service nginx reload'"
certbot_create_command: "{{ certbot_script }} certonly --webroot --webroot-path {{ nginx_www_dir }} --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.domains | join(',') }}"

erlang_series: 24
rabbitmq_version: "3.9.11"
rabbitmq_deb: "rabbitmq-server_{{ rabbitmq_version }}-1_all.deb"
rabbitmq_deb_url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v{{ rabbitmq_version }}/{{ rabbitmq_deb }}"

supervisord_unix_http_server_socket_mode: "0660"
supervisord_log_fatal_state_to_syslog: true
