---

- src: f500.debian
- src: f500.bashrc
- src: f500.locale
- src: f500.ntp
- src: f500.nginx
- src: f500.php7
- src: f500.php_composer
- src: f500.memcached
- src: f500.ufw
- src: f500.ufw_rules
- src: f500.vim

- src: HanXHX.mysql
- src: geerlingguy.certbot
- src: geerlingguy.mailhog
