---
- name: Provision vps1.markmeijerman.nl
  hosts: all
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
    - f500.debian
    - install_apt_packages
    - f500.bashrc
    - HanXHX.mysql
    - f500.nginx
    - f500.locale
    - f500.ufw
    - f500.supervisord
    - f500.memcached
    - f500.ansible_php8
    - f500.php_composer
    - f500.vim
    - f500.debian
    - rockandska.erlang
    - geerlingguy.rabbitmq
    - rabbitmq-management

  tasks:
    - name: write custom mariadb conf file
      template:
        src: my.cnf.j2
        dest: /etc/mysql/mariadb.conf.d/90-my.cnf

    - name: "copy logrotate configuration"
      copy:
        src: "logrotate-nginx"
        dest: "/etc/logrotate.d/nginx"
        mode: "0644"

- name: Production roles
  hosts: "production"
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
    - webserver
    - geerlingguy.certbot
    - lets_encrypt
