---
- name: Provision vps2.markmeijerman.nl
  hosts: all
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
    - f500.debian
    - install_apt_packages
    - f500.ntp
    - f500.bashrc
    - HanXHX.mysql
    - f500.nginx
    - f500.locale
    - f500.ufw
    - f500.ufw_rules
    - f500.memcached
    - f500.php7
    - f500.php_composer
    - f500.vim

- name: Import roles per project for develop
  hosts: "develop"
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
      - geerlingguy.mailhog

- name: Import roles per project for develop
  hosts: "develop"
  remote_user: "{{ ssh_provision_user }}"
  become: no

  tasks:
    - name: Use role in loop voor develop
      include_role:
        name: '{{ item }}'
      loop: '{{ synced_projects }}'

- name: Production roles
  hosts: "production"
  remote_user: "{{ ssh_provision_user }}"
  become: yes

  roles:
    - webserver
    - geerlingguy.certbot
    - lets_encrypt

  tasks:
    - name: Import roles per project for production
      include_role:
        name: "{{ item }}"
      loop: "{{ lookup('pipe', 'ls -1 ' + inventory_dir + '/roles-per-project').split('\n') }}"
