---

- name: Create sessions dev dir
  file: path=/dev/shm/donarteamcup/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/donarteamcup/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dir
  file: path=/dev/shm/donarteamcup/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Copy the parameters distfile
  command: cp /vagrant/donarteamcup/app/config/parameters.yml.dist /vagrant/donarteamcup/app/config/parameters.yml creates=/vagrant/donarteamcup/app/config/parameters.yml

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/donarteamcup

- name: Install assets
  command: php bin/console assets:install web --symlink chdir=/vagrant/donarteamcup

- name: Doctrine migrations
  command: bin/console doctrine:migrations:migrate --no-interaction chdir=/vagrant/donarteamcup
