---

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  when: php7_enable_apache

- name: Restart PHP FPM
  service:
    name: "php{{ php7_version }}-fpm"
    state: restarted
  when: php7_enable_fpm
