---

- name: Legacy config failure
  fail: msg="Legacy variable ufw_rules_allow_ports is no longer supported. You MUST upgrade to ufw_rules_to_create and ufw_rules_to_delete. The format has changed, so please check the documentation for more information."
  when: ufw_rules_allow_ports is defined

- name: set default policy
  ufw:
    policy: "{{ ufw_rules_default_policy }}"

- name: create rules
  ufw:
    direction: "{{ item.direction|default(omit) }}"
    from_ip: "{{ item.from_ip|default(omit) }}"
    from_port: "{{ item.from_port|default(omit) }}"
    interface: "{{ item.interface|default(omit) }}"
    proto: "{{ item.proto|default(omit) }}"
    rule: "{{ item.rule|default('allow') }}"
    to_ip: "{{ item.to_ip|default(omit) }}"
    to_port: "{{ item.to_port|default(omit) }}"
  with_items: "{{ ufw_rules_to_create }}"

- name: delete rules
  ufw:
    direction: "{{ item.direction|default(omit) }}"
    from_ip: "{{ item.from_ip|default(omit) }}"
    from_port: "{{ item.from_port|default(omit) }}"
    interface: "{{ item.interface|default(omit) }}"
    proto: "{{ item.proto|default(omit) }}"
    rule: "{{ item.rule|default('allow') }}"
    to_ip: "{{ item.to_ip|default(omit) }}"
    to_port: "{{ item.to_port|default(omit) }}"
    delete: yes
  with_items: "{{ ufw_rules_to_delete }}"
