nginx_server_templates_donargym:
  - name: donargym
    src: "{{ inventory_dir }}/roles-per-project/webserver/templates/http.conf.j2"
    ssl: off
    index: app_dev.php
    web_root: "{{ project_root}}/donargym/web"
    domains:
      - "donargym.loc"
      - "www.donargym.loc"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com data:"

donargym_db_user:     'donargym'
donargym_db_password: 'donargym'

mariadb_databases_donargym:
  - 'donargym'

mariadb_users_donargym:
  - {
    name:     "{{ donargym_db_user }}",
    password: "{{ donargym_db_password }}",
    priv:     "donargym.*:ALL",
    host:     "%"
  }
