nginx_server_templates_donarteamcup:
  - name: donarteamcup
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: app_dev.php
    web_root: "{{ project_root}}/donarteamcup/web"
    domains:
      - "donarteamcup.loc"
      - "www.donarteamcup.loc"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com data:"

donarteamcup_db_user:     'donarteamcup'
donarteamcup_db_password: 'donarteamcup'

mariadb_databases_donarteamcup:
  - 'donarteamcup'

mariadb_users_donarteamcup:
  - {
    name:     "{{ donarteamcup_db_user }}",
    password: "{{ donarteamcup_db_password }}",
    priv:     "donarteamcup.*:ALL",
    host:     "%"
  }
