nginx_server_templates_thog:
  - name: thog
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    ssl: off
    index: app_dev.php
    web_root: "{{ project_root}}/thog/web"
    domains:
      - "thog.loc"
      - "www.thog.loc"
    headers:
      Content-Security-Policy: "default-src https://www.google-analytics.com 'self'; script-src https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com code.jquery.com cdn.jsdelivr.net 'self' 'unsafe-inline'; style-src cdn.jsdelivr.net 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"

thog_db_user:     'thog'
thog_db_password: 'thog'

mariadb_databases_thog:
  - 'thog'

mariadb_users_thog:
  - {
    name:     "{{ thog_db_user }}",
    password: "{{ thog_db_password }}",
    priv:     "thog.*:ALL",
    host:     "%"
  }
