---

- name: Create sessions dev dir
  file: path=/dev/shm/donargym/var/sessions/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create cache dev dir
  file: path=/dev/shm/donargym/var/cache/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Create logs dir
  file: path=/dev/shm/donargym/var/logs/ recurse=yes group=vagrant owner=vagrant state=directory
  become: yes

- name: Copy the parameters distfile
  command: cp /vagrant/donargym/app/config/parameters.yml.dist /vagrant/donargym/app/config/parameters.yml creates=/vagrant/donargym/app/config/parameters.yml

- name: Composer install
  command: composer install --no-interaction --prefer-source --no-scripts --working-dir=/vagrant/donargym

- name: Install assets
  command: php app/console assets:install web --symlink chdir=/vagrant/donargym
