---

nginx_server_templates_donarteamcup_test:
  - name: donarteamcup_test
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/test.donarteamcup.nl/current/web"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src code.jquery.com cdn.jsdelivr.net 'self' 'unsafe-inline'; style-src cdn.jsdelivr.net 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "test.donarteamcup.nl"

donarteamcup_test_db_user:     ~ # Placed in secure.yml
donarteamcup_test_db_password: ~ # Placed in secure.yml

mariadb_databases_donarteamcup_test:
  - donarteamcuptest

mariadb_users_donarteamcup_test:
  - {
    name:     "{{ donarteamcup_test_db_user }}",
    password: "{{ donarteamcup_test_db_password }}",
    priv:     "donarteamcuptest.*:ALL",
    host:     "%"
  }
