---

nginx_server_templates_haagsedonarcup_test:
  - name: haagsedonarcup_test
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/test.haagsedonarcup.nl/current/web"
    headers:
        Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "test.haagsedonarcup.nl"

haagsedonarcup_test_db_user:     ~ # Placed in secure.yml
haagsedonarcup_test_db_password: ~ # Placed in secure.yml

mariadb_databases_haagsedonarcup_test:
  - haagsedonarcupTest

mariadb_users_haagsedonarcup_test:
  - {
    name:     "{{ haagsedonarcup_test_db_user }}",
    password: "{{ haagsedonarcup_test_db_password }}",
    priv:     "haagsedonarcupTest.*:ALL",
    host:     "%"
  }
