---

nginx_server_templates_haagsedonarcup:
  - name: haagsedonarcup
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/haagsedonarcup.nl/current/web"
    headers:
      Content-Security-Policy: "default-src 'self'; script-src code.jquery.com cdn.jsdelivr.net 'self' 'unsafe-inline'; style-src cdn.jsdelivr.net 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "haagsedonarcup.nl"
        - "www.haagsedonarcup.nl"

haagsedonarcup_db_user:     ~ # Placed in secure.yml
haagsedonarcup_db_password: ~ # Placed in secure.yml

mariadb_databases_haagsedonarcup:
  - haagsedonarcup

mariadb_users_haagsedonarcup:
  - {
    name:     "{{ haagsedonarcup_db_user }}",
    password: "{{ haagsedonarcup_db_password }}",
    priv:     "haagsedonarcup.*:ALL",
    host:     "%"
  }
