---

nginx_server_templates_jurysysteem_thog_test:
  - name: jurysysteem_thog_test
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/thog-test.jurysysteem.nl/current/web"
    headers:
        Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "thog-test.jurysysteem.nl"

jurysysteem_thog_test_db_user:     ~ # Placed in secure.yml
jurysysteem_thog_test_db_password: ~ # Placed in secure.yml

mariadb_databases_jurysysteem_thog_test:
  - jurysysteem_thog_test

mariadb_users_jurysysteem_thog_test:
  - {
    name:     "{{ jurysysteem_thog_test_db_user }}",
    password: "{{ jurysysteem_thog_test_db_password }}",
    priv:     "jurysysteem_thog_test.*:ALL",
    host:     "%"
  }
