---

nginx_server_templates_jurysysteem_hdc:
  - name: jurysysteem_hdc
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/hdc.jurysysteem.nl/current/web"
    headers:
        Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "hdc.jurysysteem.nl"

jurysysteem_hdc_db_user:     ~ # Placed in secure.yml
jurysysteem_hdc_db_password: ~ # Placed in secure.yml

mariadb_databases_jurysysteem_hdc:
  - jurysysteem_hdc

mariadb_users_jurysysteem_hdc:
  - {
    name:     "{{ jurysysteem_hdc_db_user }}",
    password: "{{ jurysysteem_hdc_db_password }}",
    priv:     "jurysysteem_hdc.*:ALL",
    host:     "%"
  }
