---

deploy_user: deploy
project_root: /home/{{ deploy_user }}
bashrc_users:
  - "provision"

ssh_provision_user: "provision"

# UFW
ufw_default_policy:
  - { direction: "incoming", policy: "deny" }

ufw_rules_to_create:
  - to_port: 22 # ssh
    rule: allow
  - to_port: 80 # Nginx
    rule: allow
  - to_port: 443 # Nginx
    rule: allow

# PHP

php8_ini_directives_global:
  disable_functions:      "exec, passthru, system, popen"
  allow_url_fopen:        1
  session.save_path:      "/var/lib/php{{ php8_version }}/sessions"
  session.cookie_secure:  1
  session.gc_probability: 1
  session.gc_divisor:     1000
  session.gc_maxlifetime: 3600
  always_populate_raw_post_data: "-1"

  opcache_fast_shutdown: 0
  opcache_interned_strings_buffer: 16
  opcache_max_accelerated_files: 10240
  opcache_memory_consumption: 128
  opcache_revalidate_freq: 0
  opcache_validate_timestamps: 0

  error_log: syslog

php8_ini_directives_fpm:
  upload_max_filesize: "8M"
  post_max_size: "8M"

php8_fpm_pool_enabled: yes
php8_fpm_pool_name: www
php8_fpm_pool_user: www-data
php8_fpm_pool_group: www-data
php8_fpm_pool_listen: "/run/php/php{{ php8_version }}-fpm.sock"
php8_fpm_pool_listen_mode: "0660"
php8_fpm_pool_pm: static
php8_fpm_pool_status_path: /status
php8_fpm_pool_pm_max_children: 128
php8_fpm_pool_pm_max_requests: 512
php8_fpm_pool_catch_workers_output: yes

# MYSQL
mariadb_bind_address:          "127.0.0.1"
mariadb_root_password:         ~ # Placed in secure.yml

mariadb_databases: "{{ mariadb_databases_jurysysteem_staging + mariadb_databases_jurysysteem_donar + mariadb_databases_jurysysteem_craft + mariadb_databases_jurysysteem_production }}"
mariadb_users: "{{ mariadb_users_jurysysteem_staging + mariadb_users_jurysysteem_donar + mariadb_users_jurysysteem_craft + mariadb_users_jurysysteem_production }}"

# NGINX
nginx_user:         www-data
nginx_group:        www-data
nginx_set_default_server: false
server_templates:   "{{ nginx_server_templates_jurysysteem_staging + nginx_server_templates_jurysysteem_donar + nginx_server_templates_jurysysteem_craft + nginx_server_templates_jurysysteem_production + nginx_server_templates_default }}"

nginx_http_params:
  client_max_body_size: "8M"
  ssl_protocols: TLSv1.3

#supervisord_include_files:  "/etc/supervisor/conf.d/*.conf {{ project_root }}/zh-staging.jurysysteem.nl/shared/supervisor/*.conf {{ project_root }}/zh.jurysysteem.nl/shared/supervisor/*.conf"

#rabbitmq
rabbitmq_vhosts: []
#  - zh-jurysysteem-staging
#  - zh-jurysysteem-production

rabbitmq_management_users: []
#  - username: "zh-jurysysteem-staging"
#    password: "{{ rabbitmq_zh_jurysysteem_staging_password }}"
#    role: management
#    permissions:
#      - vhost: zh-jurysysteem-staging
#        configure_priv: .*
#        read_priv: .*
#        write_priv: .*
#  - username: "zh-jurysysteem-production"
#    password: "{{ rabbitmq_zh_jurysysteem_production_password }}"
#    role: management
#    permissions:
#      - vhost: zh-jurysysteem-production
#        configure_priv: .*
#        read_priv: .*
#        write_priv: .*
#
