---

nginx_server_templates_thog:
  - name: thog
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/thog.nl/current/web"
    headers:
        Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "thog.nl"
        - "www.thog.nl"

thog_db_user:     ~ # Placed in secure.yml
thog_db_password: ~ # Placed in secure.yml

mariadb_databases_thog:
  - thog

mariadb_users_thog:
  - {
    name:     "{{ thog_db_user }}",
    password: "{{ thog_db_password }}",
    priv:     "thog.*:ALL",
    host:     "%"
  }
