---

nginx_server_templates_thog_test:
  - name: thog_test
    src: "{{ inventory_dir }}/roles/webserver/templates/https.conf.j2"
    index: app.php
    web_root: "{{ project_root}}/test.thog.nl/current/web"
    headers:
      Content-Security-Policy: "default-src https://www.google-analytics.com 'self'; script-src https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com code.jquery.com cdn.jsdelivr.net 'self' 'unsafe-inline'; style-src cdn.jsdelivr.net 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:"
    domains:
        - "test.thog.nl"

thog_test_db_user:     ~ # Placed in secure.yml
thog_test_db_password: ~ # Placed in secure.yml

mariadb_databases_thog_test:
  - thogTest

mariadb_users_thog_test:
  - {
    name:     "{{ thog_test_db_user }}",
    password: "{{ thog_test_db_password }}",
    priv:     "thogTest.*:ALL",
    host:     "%"
  }
