---

- name: Check for absent certificates
  stat:
    path: /etc/letsencrypt/live/{{ item.domains | first }}/cert.pem
  with_items: "{{ server_templates }}"
  register: webserver_letsencrypt

- name: Write http config for domains without certificate
  template:
    src: "{{ inventory_dir }}/roles/webserver/templates/http.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ webserver_letsencrypt.results }}"
  when: "webserver_letsencrypt is defined and not item.stat.exists and (item.item.type is not defined or item.item.type != 'redirect')"

- name: Activate domains without certificate
  file:
    src: "/etc/nginx/sites-available/{{ item.item.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.item.name }}.conf"
    state: link
  with_items: "{{ webserver_letsencrypt.results }}"
  when: "webserver_letsencrypt is defined and not item.stat.exists"
  register: webserver_http_config_activate

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  when: webserver_http_config_activate is changed

- name: Stop nginx
  service:
    name: nginx
    state: stopped
  when: "webserver_letsencrypt.msg is defined and webserver_letsencrypt.msg != 'All items completed'"

- name: Create certificates
  shell: "{{ certbot_create_command }}"
  with_items: "{{ webserver_letsencrypt.results }}"
  when: "webserver_letsencrypt is defined and not item.stat.exists"

- name: Write https configs
  template:
    src: "{{ item.src }}"
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ server_templates }}"
  register: webserver_https_config_write

- name: Activate domains
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    state: link
  with_items: "{{ server_templates }}"
  register: webserver_https_config_activate

- name: Start nginx
  service:
    name: nginx
    state: started
  when: "webserver_letsencrypt.msg is defined and webserver_letsencrypt.msg != 'All items completed'"

- name: add nginx reload renew hook
  template:
    src: "{{ inventory_dir }}/roles/lets_encrypt/templates/01-reload-nginx.j2"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/01-reload-nginx"
    owner: root
    group: root
    mode: 0744
